services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=epos
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: